---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by vitaliy.
--- DateTime: 01.06.2021 14:46
---

return {
    up = function()
        local utils = require('migrator.utils')
        local f = box.schema.create_space('document', {
            format = {
                { name = 'key', type = 'string' },
                { name = 'bucket_id', type = 'unsigned' },
                { name = 'value', type = 'any', is_nullable = true }
            },
            if_not_exists = true,
        })
        f:create_index('primary', {
            parts = { 'key' },
            if_not_exists = true,
        })
        f:create_index('bucket_id', {
            parts = { 'bucket_id' },
            if_not_exists = true,
            unique = false
        })
        utils.register_sharding_key('document', {'key'})
        return true
    end
}
